# Elasticsearch plugin descriptor file
description=The ElasticSearch sink plugin for replaying CDC trigger data.
version=0.0.1-SHAPSHOT
name=CcEsSink
classname=com.clougence.cloudcanal.es6.sink.CcEs6SinkPlugin
java.version=1.8
elasticsearch.version=6.8.23
